[package]
name = "chat_r"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
serde = { version = "1.0.148", features = ["derive"] }
rmp-serde = "1.1.1"
nanoid = "0.4.0"
iced = "0.6.0"